### ISSUE TITLE
Renpy 8 Migration

### ISSUE THREAD

**Issue by multimokia** [Just-Natsuki-Team/NatsukiModDev#376]
Ideally speaking, we should migrate JN to Renpy 8 as Python 2 has been out of service for over 2 years at this point, thus rendering all libraries for it as unmaintained and unsupported. This makes future expansion in terms of integration through the use of other libraries impossible, or not-guaranteed to work with no support for them.

Renpy 8 however, has upgraded python from version 2.7 to version 3.10

To migrate to renpy 8, we must ensure compatibility with python 3 syntax, this means and methods like `.iterkeys()`, `iteritems()`, or `itervalues()` should be replaced with `.keys()`, `.items()`. and `.values()` (on dicts)

Additionally, these new functions return `dict_keys`, `dict_items`, and `dict_values` objects respectively, and these _cannot_ be indexed as they are iterators instead of lists.

As such, if we require indexing the results of these methods, they must be wrapped in a `list()` or `tuple()` constructor.

# TODO:
- [ ] Ensure all existing code adheres to python 3 syntax
- [ ] Update docker image to use the latest distribution of renpy 8 so we can run CI tests with it
- [ ] Update all of our libraries to use the latest python 3 versions

**Comment by FrancitiX** [comment]
Hi there, I wanna know if someone is already doing the migration.
